### ISSUE TITLE
Instancing more than one AAS

### ISSUE THREAD

**Issue by AnVentura** [FraunhoferIOSB/FAAAST-Service#913] opened 2024-10-03 22:14 UTC
I am currently implementing a project using the FAAAST service and I am looking for assistance. My goal is to ensure that, upon starting the program, more than one Asset Administration Shell (AAS) is instantiated. I have AASs stored both locally and online, and I would like to configure the service so that all of these AASs are available in FAAAST upon startup, rather than just a single instance.

Is there a way to achieve this multiple instantiation of AASs?

Thank you in advance for your support.
Best regards, 
André Ventura

**Comment by mjacoby** [comment] 2024-10-07 06:52
FA³ST Service is started with an AAS Environment file which can contain any number of Asset Administration Shells, Submodels, and Concept Descriptions. However, currently only a single such file can be passed. 
I assume that you have multiple files containing each a single AAS and the respective submodels. In this case, the only way to start all of them at once using FA³ST Service is to manually merge these AAS files to a single one before passing them to FA³ST Service.

However, the feature to start FA³ST Service with multiple AAS files as input is in our backlog but not with the highest priority. Also, it is also not trivial because e.g. one needs to implement such a merging algorithm that detects inconsistencies while merging and it is unclear how file-based persistence should work with multiple files in some cases.

As a consequence, it probably will require to rethink the whole process how FA³ST Service is loading models and how file-based persistence works.

This also seems to be the same feature request as in https://github.com/FraunhoferIOSB/FAAAST-Service/issues/172

**Comment by mjacoby** [comment] 2024-10-16 06:30
Closed because duplicate of #172

**Closed by mjacoby** 2024-10-16 06:30 UTC
Labels: enhancement
