### ISSUE TITLE
Fa³st Service does not start with OPC UA Endpoint when several ConceptDescriptions 

### ISSUE THREAD

**Issue by wildias12** [FraunhoferIOSB/FAAAST-Service#800] opened 2024-06-11 14:06 UTC
**Description:**
The Fa³st Service fails to start correctly when there are a large number of ConceptDescriptions in the OPC UA endpoint. This issue was identified during testing, where the service could not handle a high volume of ConceptDescriptions.

**Steps to Reproduce:**

1. Configure Fa³st Service with an AASX model containing multiple ConceptDescriptions.

1. In my case, the applied model has 216 ConceptDescriptions.

**Expected Behavior:**
The service should start correctly and handle a large number of ConceptDescriptions without errors.

**Actual Behavior:**
The service fails to start, presenting errors that prevent it from functioning properly when there are many ConceptDescriptions.

**Environment:**

- The service starts running, showing that the model is validated.

- The HTTP endpoints are correctly raised.

- The service is unable to generate its own OPC UA server.

- Fa³st Service version: 1.0.1

- AAS Package Explorer version: 3

- Operating System: Windows 10 Home

**Relevant Logs:**
Below are the logs showing the errors encountered when starting the service with a large number of ConceptDescriptions:

**Relevant Logs:**
![image](https://github.com/FraunhoferIOSB/FAAAST-Service/assets/172388426/2e0ce2eb-c22d-470f-9bff-c965c1dba83f)
Log description: Service running with the intended model.

![image](https://github.com/FraunhoferIOSB/FAAAST-Service/assets/172388426/86ef2560-86eb-48d6-88de-be6fccc44b22)
Log description: Final command lines before the service fails to generate the OPC UA server.

**Comment by mjacoby** [comment] 2024-06-12 06:19
Could you please provide an example model file to reproduce this issue?
If this is not possible, please run FA³ST with the additional argument `--loglevel-faaast TRACE` and post the output.

**Comment by wildias12** [comment] 2024-06-12 14:08
Hi Jacoby,
I hope this message finds you well.
I am writing this report upon the request of your colleague, Tino Bischoff. As a partner of AIMEN and a collaborator on the European project Circular Tw4In, I have previously communicated the limitations encountered. Tino suggested that I report these issues to you.
Attached, you will find the model used for testing, which is the model of a robot.
Regarding the implementation of the argument "--loglevel-faaast TRACE," there was no noticeable difference from the print attached to the report.
Should you require any further information from my side, please feel free to contact me.
Thank you very much.
Best regards,

________________________________
De: Michael Jacoby ***@***.***>
Enviado: 12 de junho de 2024 07:20
Para: FraunhoferIOSB/FAAAST-Service ***@***.***>
Cc: wildias12 ***@***.***>; Author ***@***.***>
Assunto: Re: [FraunhoferIOSB/FAAAST-Service] Fa³st Service does not start with OPC UA Endpoint when several ConceptDescriptions (Issue #800)


Could you please provide an example model file to reproduce this issue?
If this is not possible, please run FA³ST with the additional argument --loglevel-faaast TRACE and post the output.

**Comment by mjacoby** [comment] 2024-06-13 08:24
I seems that you responded to the automated Github email and attached the example data there, i.e. it is not available online and I cannot access it. Please either upload the file via Browser on the Github issue or if you prefer (or it may contain sensitive information you do not want to be made public) send it via email to faaast@iosb.fraunhofer.de

**Comment by mjacoby** [comment] 2024-06-14 11:41
@wildias12 Thank you for providing an example model via email.
This issue was indeed caused by a bug in FA³ST but it is fixed on the main branch and in the latest snapshot release.

Please verify that it is now working as expected by either 

- checking out the latest code on the main branch and manually compile
- downloading the [latest pre-compiled snapshot version](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=de.fraunhofer.iosb.ilt.faaast.service&a=starter&v=1.1.0-SNAPSHOT)
- or testing with the docker container (tag `:latest` or `:1.1.0-SNAPSHOT`, make sure to call `docker pull`)

**Comment by wildias12** [comment] 2024-06-14 13:36
Hi @mjacoby,

Thank you for the explanation. I tested with the recommended version, and it indeed allows reading the provided model now. I will continue to use the FA³ST service and will reach out again if I have any further questions.

Thanks for the quick resolution!

**Closed** 2024-06-17 06:30 UTC
Labels: bug
